SPOOL_PRESETS = [
    {"name": "123-3D (Standard)", "weight": 216},
    {"name": "123-3D (Purefil)", "weight": 100},
    {"name": "3DJake (ecoPLA/Magic)", "weight": 240},
    {"name": "3DJake (niceBio)", "weight": 207},
    {"name": "3DXtech (Standard)", "weight": 260},
    {"name": "3DXtech (CarbonX)", "weight": 310},
    {"name": "3DXtech (PC)", "weight": 286},
    {"name": "3DXtech (PVA)", "weight": 120},
    {"name": "Addnorth", "weight": 244},
    {"name": "Amazon Basics", "weight": 231},
    {"name": "Anycubic", "weight": 126},
    {"name": "AzureFilm", "weight": 220},
    {"name": "Bambu Lab (Reusable)", "weight": 250},
    {"name": "ColorFabb", "weight": 240},
    {"name": "CR3D", "weight": 248},
    {"name": "DasFilament (Standard)", "weight": 215},
    {"name": "DasFilament (Large)", "weight": 250},
    {"name": "Devil Design", "weight": 250},
    {"name": "Eryone", "weight": 192},
    {"name": "eSun (Plastic)", "weight": 240},
    {"name": "eSun (ABS+)", "weight": 230},
    {"name": "Extrudr (NX2/DuraPro)", "weight": 260},
    {"name": "Fillamentum", "weight": 230},
    {"name": "Formfutura", "weight": 208},
    {"name": "Inland", "weight": 209},
    {"name": "Matter3D", "weight": 140},
    {"name": "Ninjatek", "weight": 330},
    {"name": "Novamaker", "weight": 184},
    {"name": "Overture (Cardboard)", "weight": 170},
    {"name": "Paramount3D", "weight": 230},
    {"name": "Polyalkemi", "weight": 226},
    {"name": "PolyMaker (PolyLite/Terra)", "weight": 140},
    {"name": "PolySmart", "weight": 161},
    {"name": "Prima", "weight": 250},
    {"name": "Printed Solid (Jessie)", "weight": 295},
    {"name": "Prusament", "weight": 190},
    {"name": "R3D", "weight": 192},
    {"name": "Smartfil", "weight": 240},
    {"name": "Sunlu", "weight": 152}
]
