SPOOL_PRESETS = [
    {"name": "123-3D (Purefil)", "weight": 100},
    {"name": "123-3D (Standard)", "weight": 216},
    {"name": "3D FilaPrint (Pappe, 1 kg)", "weight": 210},
    {"name": "3D FilaPrint (Plastik, 1 kg)", "weight": 238},
    {"name": "3D Fuel (Plastik, 1 kg)", "weight": 264},
    {"name": "3D Genius (Pappe, 1 kg)", "weight": 160},
    {"name": "3D Jake (Pappe, 1 kg)", "weight": 209},
    {"name": "3D Jake (Plastik, 1 kg)", "weight": 229},
    {"name": "3D Jake (Plastik, 250 g)", "weight": 91},
    {"name": "3D Jake EcoPLA (Plastik, 1 kg)", "weight": 225},
    {"name": "3D Power (Plastik, 1 kg)", "weight": 220},
    {"name": "3D Solutech (Plastik, 1 kg)", "weight": 173},
    {"name": "3DE (Pappe, 1 kg)", "weight": 136},
    {"name": "3DE (Plastik, 1 kg)", "weight": 181},
    {"name": "3DHOJOR (Pappe, 1 kg)", "weight": 160},
    {"name": "3DJake (ecoPLA/Magic)", "weight": 240},
    {"name": "3DJake (niceBio)", "weight": 207},
    {"name": "3DXtech (CarbonX)", "weight": 310},
    {"name": "3DXtech (PC)", "weight": 286},
    {"name": "3DXtech (PVA)", "weight": 120},
    {"name": "3DXtech (Standard)", "weight": 260},
    {"name": "3DXTech (Plastik, 1 kg)", "weight": 264},
    {"name": "3DXTech (Plastik, 750 g)", "weight": 295},
    {"name": "Acccreate (Plastik, 1 kg)", "weight": 181},
    {"name": "Addnorth", "weight": 244},
    {"name": "AIO Robotics (Plastik, 250 g)", "weight": 120},
    {"name": "Alfawise (Plastik, 1 kg)", "weight": 174},
    {"name": "Alzament (Pappe, 1 kg)", "weight": 150},
    {"name": "Amazon Basics", "weight": 231},
    {"name": "Amazon Basics (Plastik, 1 kg)", "weight": 212},
    {"name": "American Filament (Plastik, 1 kg)", "weight": 315},
    {"name": "Amolen (Plastik, 1 kg)", "weight": 170},
    {"name": "Amolen (Plastik, 800 g)", "weight": 61},
    {"name": "AMZ3D (Plastik, 1 kg)", "weight": 233},
    {"name": "Anycubic (Pappe, 1 kg)", "weight": 125},
    {"name": "Anycubic (Plastik, 1 kg)", "weight": 127},
    {"name": "Artillery (Pappe, 1 kg)", "weight": 156},
    {"name": "Atomic Filament (Plastik, 1 kg)", "weight": 298},
    {"name": "AURAPOL (Plastik, 1 kg)", "weight": 225},
    {"name": "Aurarum (Plastik Durchsichtig, 1 kg)", "weight": 224},
    {"name": "AzureFilm", "weight": 220},
    {"name": "Azurefilm (Plastik Schwarz, 1 kg)", "weight": 223},
    {"name": "Azurefilm (Plastik Durchsichtig Neu, 1 kg)", "weight": 232},
    {"name": "Azurefilm (Plastik Durchsichtig, 1 kg)", "weight": 163},
    {"name": "Bambu Lab (Reusable)", "weight": 250},
    {"name": "BQ (Plastik Durchsichtig, 1 kg)", "weight": 218},
    {"name": "CC3D (Plastik, 1 kg)", "weight": 171},
    {"name": "Coex3D (Pappe, 1 kg)", "weight": 190},
    {"name": "ColorFabb", "weight": 240},
    {"name": "Colorfabb (Pappe, 750 g)", "weight": 152},
    {"name": "Colorfabb (Plastik, 1 kg)", "weight": 236},
    {"name": "Colorfabb (Plastik, 2.2 kg)", "weight": 602},
    {"name": "Colorfabb (Plastik, 4.5 kg)", "weight": 700},
    {"name": "Colorfabb (Plastik, 750 g)", "weight": 256},
    {"name": "Colorfabb (Plastik, 8 kg)", "weight": 1050},
    {"name": "Colorful (Plastik, 1 kg)", "weight": 163},
    {"name": "Comgrow (Pappe, 1 kg)", "weight": 166},
    {"name": "CR3D", "weight": 248},
    {"name": "Creality (Pappe, 1 kg)", "weight": 170},
    {"name": "Creality (Plastik Schwarz, 1 kg)", "weight": 171},
    {"name": "Creality (Plastik Durchsichtig, 1 kg)", "weight": 158},
    {"name": "Das Filament (Plastik, 1 kg)", "weight": 211},
    {"name": "DasFilament (Groß)", "weight": 250},
    {"name": "DasFilament (Standard)", "weight": 215},
    {"name": "Devil Design", "weight": 250},
    {"name": "Devil Designs (Plastik, 1 kg)", "weight": 256},
    {"name": "DoWell3D (Plastik, 1 kg)", "weight": 182},
    {"name": "Duramic 3D (Pappe, 1 kg)", "weight": 141},
    {"name": "EasyThreed (Plastik, 250 g)", "weight": 53},
    {"name": "EcoLine (Plastik, 1 kg)", "weight": 283},
    {"name": "Eibos (Plastik Durchsichtig, 1 kg)", "weight": 184},
    {"name": "Elegoo (Pappe, 1 kg)", "weight": 158},
    {"name": "Elegoo (Plastik, 1 kg)", "weight": 114},
    {"name": "Ender (Plastik, 1 kg)", "weight": 88},
    {"name": "Eryone", "weight": 192},
    {"name": "Eryone (Pappe, 1 kg)", "weight": 172},
    {"name": "Eryone (Pappe, 250 g)", "weight": 86},
    {"name": "Eryone (Plastik, 1 kg)", "weight": 227},
    {"name": "Essentium (Plastik, 1 kg)", "weight": 225},
    {"name": "Essentium (Plastik, 2.5 kg)", "weight": 918},
    {"name": "Essentium (Plastik, 4 kg)", "weight": 920},
    {"name": "Essentium (Plastik, 750 g)", "weight": 365},
    {"name": "eSun (ABS+)", "weight": 230},
    {"name": "eSun (Plastik)", "weight": 240},
    {"name": "eSUN (Pappe, 1 kg)", "weight": 161},
    {"name": "eSUN (Plastik Schwarz, 1 kg)", "weight": 253},
    {"name": "eSUN (Plastik Schwarz, 500 g)", "weight": 212},
    {"name": "eSUN (Plastik Durchsichtig, 1 kg)", "weight": 217},
    {"name": "eSUN (Plastik Durchsichtig, 500 g)", "weight": 203},
    {"name": "eSUN (Plastik eSpool+, 1 kg)", "weight": 212},
    {"name": "eSUN (Plastik, 1 kg)", "weight": 224},
    {"name": "eSUN (Plastik, 2.5 kg)", "weight": 634},
    {"name": "Extrudr (NX2/DuraPro)", "weight": 260},
    {"name": "Extrudr (Plastik, 1 kg)", "weight": 252},
    {"name": "F3D (Plastik, 200 g)", "weight": 130},
    {"name": "FCC (Plastik, 750 g)", "weight": 206},
    {"name": "Fiberlogy (Plastik ABS, 1 kg)", "weight": 260},
    {"name": "Fiberlogy (Plastik Donut, 1 kg)", "weight": 322},
    {"name": "Fiberon PolyMaker (Pappe, 1 kg)", "weight": 168},
    {"name": "Filament PM (Plastik, 1 kg)", "weight": 224},
    {"name": "Filament PM (Plastik, 2 kg)", "weight": 599},
    {"name": "Filament PM (Plastik, 300 g)", "weight": 131},
    {"name": "Filament PM (Plastik, 500 g)", "weight": 208},
    {"name": "Filament PM (Plastik, 750 g)", "weight": 231},
    {"name": "Filanora (Plastik, 1 kg)", "weight": 178},
    {"name": "Fillamentum", "weight": 230},
    {"name": "Fillamentum (Plastik, 750 g)", "weight": 235},
    {"name": "Flashforge (Plastik, 1 kg)", "weight": 169},
    {"name": "Formfutura", "weight": 208},
    {"name": "FormFutura (Pappe, 1 kg)", "weight": 155},
    {"name": "FormFutura (Plastik, 750 g)", "weight": 212},
    {"name": "Fusion Filaments (Plastik, 1 kg)", "weight": 235},
    {"name": "Geeetech (Plastik, 1 kg)", "weight": 187},
    {"name": "Gembird (Pappe, 1 kg)", "weight": 143},
    {"name": "GIANTARM (Plastik, 1 kg)", "weight": 186},
    {"name": "GNVTNTP (Pappe, 1 kg)", "weight": 156},
    {"name": "GratKit (Pappe, 1 kg)", "weight": 155},
    {"name": "Greeny+ (Pappe, 2.5 kg)", "weight": 372},
    {"name": "GST3D (Plastik, 1 kg)", "weight": 206},
    {"name": "Hatchbox (Plastik, 1 kg)", "weight": 235},
    {"name": "Hello3D (Plastik, 1 kg)", "weight": 210},
    {"name": "Honeycomb Drone (Plastik, 1 kg)", "weight": 183},
    {"name": "HP 3D Printing (Plastik, 1 kg)", "weight": 187},
    {"name": "iBOSS (Plastik Durchsichtig, 1 kg)", "weight": 187},
    {"name": "IIID MAX (Plastik, 1 kg)", "weight": 138},
    {"name": "Inland", "weight": 209},
    {"name": "Inland Micro Center (Pappe VN, 1 kg)", "weight": 214},
    {"name": "Inland Micro Center (Pappe, 1 kg)", "weight": 142},
    {"name": "Inland Micro Center (Plastik Schwarz, 1 kg)", "weight": 217},
    {"name": "Inland Micro Center (Plastik Durchsichtig, 1 kg)", "weight": 215},
    {"name": "Innofil 3D (Plastik, 750 g)", "weight": 215},
    {"name": "iSANMATE (Plastik Durchsichtig, 1 kg)", "weight": 152},
    {"name": "Jamg He (Pappe, 1 kg)", "weight": 157},
    {"name": "Jayo (Pappe, 1 kg)", "weight": 128},
    {"name": "Jayo (Plastik, 1 kg)", "weight": 126},
    {"name": "Jayo (Plastik, 250 g)", "weight": 58},
    {"name": "Jessie Printed Solid (Pappe, 1 kg)", "weight": 230},
    {"name": "Jessie Printed Solid (Plastik, 1 kg)", "weight": 320},
    {"name": "Kexcelled (Pappe, 1 kg)", "weight": 204},
    {"name": "Kexcelled (Plastik, 1 kg)", "weight": 240},
    {"name": "Kingroon (Pappe, 1 kg)", "weight": 155},
    {"name": "Kingroon (Plastik, 1 kg)", "weight": 166},
    {"name": "Kiwi 3D (Plastik, 1 kg)", "weight": 194},
    {"name": "KVP (Plastik Schwarz, 1 kg)", "weight": 337},
    {"name": "KVP (Plastik Durchsichtig, 1 kg)", "weight": 263},
    {"name": "Longer (Plastik, 1 kg)", "weight": 195},
    {"name": "MadeSolid (Plastik, 1 kg)", "weight": 345},
    {"name": "Matter Hackers Build Series (Plastik, 1 kg)", "weight": 215},
    {"name": "Matter Hackers Quantum Series (Plastik, 1 kg)", "weight": 217},
    {"name": "Matter3D", "weight": 140},
    {"name": "Matter3D (Pappe, 1 kg)", "weight": 157},
    {"name": "Matter3D (Plastik, 1 kg)", "weight": 155},
    {"name": "MG Chemicals (Pappe, 1 kg)", "weight": 150},
    {"name": "MG Chemicals (Plastik, 1 kg)", "weight": 245},
    {"name": "MG Chemicals (Plastik, 200 g)", "weight": 136},
    {"name": "Mika3D (Plastik, 1 kg)", "weight": 175},
    {"name": "Mika3D (Plastik, 250 g)", "weight": 61},
    {"name": "Mika3D (Plastik, 500 g)", "weight": 110},
    {"name": "MonoPrice (Plastik, 1 kg)", "weight": 221},
    {"name": "NinjaFlex (Plastik, 500 g)", "weight": 329},
    {"name": "Ninjatek", "weight": 330},
    {"name": "Nova3D (Pappe Core Only, 1 kg)", "weight": 38},
    {"name": "Nova3D (Plastik w/ Pappe Core, 1 kg)", "weight": 159},
    {"name": "Novamaker", "weight": 184},
    {"name": "Numakers (Plastik, 1 kg)", "weight": 199},
    {"name": "NuNus 3D (Plastik, 1 kg)", "weight": 195},
    {"name": "Octave (Plastik, 1 kg)", "weight": 168},
    {"name": "Overture (Pappe)", "weight": 170},
    {"name": "Overture (Pappe, 1 kg)", "weight": 162},
    {"name": "Overture (Plastik, 1 kg)", "weight": 237},
    {"name": "OVV3D (Pappe, 1 kg)", "weight": 130},
    {"name": "OVV3D (Pappe, 200 g)", "weight": 76},
    {"name": "OWL (Plastik, 1 kg)", "weight": 203},
    {"name": "Paramount3D", "weight": 230},
    {"name": "Pinball (Pappe, 1 kg)", "weight": 140},
    {"name": "Pinball (Plastik White, 1 kg)", "weight": 171},
    {"name": "Plastspaw (Plastik, 1 kg)", "weight": 214},
    {"name": "Plexiwire (Pappe, 300 g)", "weight": 91},
    {"name": "Polyalchemy (Plastik, 750 g)", "weight": 219},
    {"name": "Polyalkemi", "weight": 226},
    {"name": "PolyMaker (Pappe, 1 kg)", "weight": 155},
    {"name": "PolyMaker (Pappe, 3 kg)", "weight": 440},
    {"name": "PolyMaker (Plastik, 1 kg)", "weight": 233},
    {"name": "PolyMaker (PolyLite/Terra)", "weight": 140},
    {"name": "PolySmart", "weight": 161},
    {"name": "Prima", "weight": 250},
    {"name": "PrimaSelect (Plastik, 1 kg)", "weight": 222},
    {"name": "Priline (Plastik, 1 kg)", "weight": 247},
    {"name": "Print Bed (Pappe, 1 kg)", "weight": 217},
    {"name": "Printed Solid", "weight": 295},
    {"name": "ProtoPasta (Pappe, 1 kg)", "weight": 80},
    {"name": "ProtoPasta (Pappe, 500 g)", "weight": 84},
    {"name": "Prusament", "weight": 190},
    {"name": "Prusament (Plastik mit Pappkern, 1 kg)", "weight": 196},
    {"name": "Prusament (Plastik mit Pappkern, 2 kg)", "weight": 209},
    {"name": "Prusament (Plastik, 1 kg)", "weight": 201},
    {"name": "Qidi (Plastik Durchsichtig, 1 kg)", "weight": 193},
    {"name": "Qidi (Plastik Durchsichtig, 500 g)", "weight": 190},
    {"name": "R3D", "weight": 192},
    {"name": "Raised 3D (Plastik, 1 kg)", "weight": 246},
    {"name": "RatRig (Plastik, 1 kg)", "weight": 220},
    {"name": "Redline (Pappe, 500 g)", "weight": 171},
    {"name": "Reprapper (Plastik, 1 kg)", "weight": 157},
    {"name": "Rosa3D (Plastik, 1 kg)", "weight": 245},
    {"name": "Sainsmart (Plastik Schwarz, 800 g)", "weight": 173},
    {"name": "Sainsmart (Plastik White, 800 g)", "weight": 153},
    {"name": "Sakata3D (Plastik Durchsichtig, 1 kg)", "weight": 253},
    {"name": "Sakata3D (Plastik Grey, 1 kg)", "weight": 205},
    {"name": "Siddament (Pappe, 1 kg)", "weight": 125},
    {"name": "Siraya Tech (Pappe, 1 kg)", "weight": 176},
    {"name": "Smartfil", "weight": 240},
    {"name": "SmartMaterials (Plastik, 1 kg)", "weight": 235},
    {"name": "SMW3D (Plastik, 1 kg)", "weight": 254},
    {"name": "Snapmaker (Pappe, 1 kg)", "weight": 148},
    {"name": "Sovol (Pappe, 1 kg)", "weight": 145},
    {"name": "Spectrum (Pappe, 1 kg)", "weight": 180},
    {"name": "Spectrum (Pappe, 2 kg)", "weight": 420},
    {"name": "Spectrum (Plastik Schwarz, 4.5 kg)", "weight": 780},
    {"name": "Spectrum (Plastik Schwarz, 8 kg)", "weight": 1020},
    {"name": "Spectrum (Plastik Durchsichtig, 1 kg)", "weight": 259},
    {"name": "Spectrum (Plastik Durchsichtig, 2 kg)", "weight": 597},
    {"name": "Spectrum (Plastik Durchsichtig, 250 g)", "weight": 120},
    {"name": "Spectrum (Plastik Durchsichtig, 500 g)", "weight": 240},
    {"name": "Spectrum (Plastik Gray, 1 kg)", "weight": 206},
    {"name": "StrongHero 3D (Plastik, 1 kg)", "weight": 138},
    {"name": "Stronghold (Plastik, 1 kg)", "weight": 205},
    {"name": "Sunlu", "weight": 152},
    {"name": "Sunlu (Plastik 2.0, 1 kg)", "weight": 178},
    {"name": "Sunlu (Plastik 3.0 mit Pappe, 1 kg)", "weight": 227},
    {"name": "Sunlu (Plastik 3.0, 1 kg)", "weight": 188},
    {"name": "Sunlu (Plastik, 1 kg)", "weight": 134},
    {"name": "Sunlu (Plastik, 2.7 kg)", "weight": 284},
    {"name": "Sunlu (Plastik, 250 g)", "weight": 55},
    {"name": "Sunlu (Plastik, 500 g)", "weight": 95},
    {"name": "The Filament Spectrum (Plastik, 1 kg)", "weight": 208},
    {"name": "TM Filament (Plastik Durchsichtig, 1 kg)", "weight": 260},
    {"name": "TTYT3D (Pappe, 1 kg)", "weight": 121},
    {"name": "TTYT3D (Plastik, 1 kg)", "weight": 190},
    {"name": "UltiMaker (Plastik, 1 kg)", "weight": 235},
    {"name": "UltiMaker (Plastik, 750 g)", "weight": 232},
    {"name": "Voolt3D (Plastik, 1 kg)", "weight": 190},
    {"name": "Voxel (Plastik, 1 kg)", "weight": 221},
    {"name": "Voxelab (Plastik, 1 kg)", "weight": 171},
    {"name": "Wanhao (Plastik, 1 kg)", "weight": 270},
    {"name": "Wasp (Plastik, 1 kg)", "weight": 214},
    {"name": "Winkle HD (Plastik, 1 kg)", "weight": 219},
    {"name": "XYZ Printing (Plastik, 600 g)", "weight": 180},
    {"name": "Yuaneang (Plastik, 1 kg)", "weight": 202},
    {"name": "Ziro (Plastik, 1 kg)", "weight": 196},
    {"name": "ZYLtech (Plastik 5-Spoke, 1 kg)", "weight": 94},
    {"name": "ZYLtech (Plastik, 1 kg)", "weight": 179}
]